[package]
name = "dummy_cc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
edit-distance = "2.1.0"
rand = "0.8.5"
